name: py38_ssl
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=openblas
  - brotlipy=0.7.0=py38h0a891b7_1005
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py38h578d9bd_1
  - cryptography=39.0.0=py38h1724139_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - docker-pycreds=0.4.0=py_0
  - faiss=1.7.2=py38cuda102h4abd241_0_cuda
  - gitdb=4.0.10=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=8_openblas
  - libfaiss=1.7.2=cuda102hd37495c_0_cuda
  - libfaiss-avx2=1.7.2=cuda102h1234567_0_cuda
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - liblapack=3.9.0=8_openblas
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libprotobuf=3.20.1=h4ff587b_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - ncurses=6.3=h7f8727e_2
  - networkx=2.8.4=py38h06a4308_0
  - numpy-base=1.21.5=py38hb8be1f0_2
  - openblas=0.3.12=pthreads_h43bd3aa_1
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py38h06a4308_0
  - promise=2.3=py38h578d9bd_7
  - psutil=5.9.4=py38h0a891b7_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_5
  - python=3.8.13=h12debd9_0
  - python_abi=3.8=2_cp38
  - pyyaml=6.0=py38h0a891b7_5
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=pyhd8ed1ab_1
  - setproctitle=1.3.2=py38h0a891b7_1
  - setuptools=65.5.0=py38h06a4308_0
  - shortuuid=1.0.11=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.4.0=pyha770c72_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - cachetools==5.2.0
    - contourpy==1.0.6
    - cycler==0.11.0
    - einops==0.6.0
    - filelock==3.8.0
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - gitpython==3.1.29
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - h5py==3.7.0
    - huggingface-hub==0.11.0
    - hydra-core==1.2.0
    - importlib-metadata==5.1.0
    - importlib-resources==5.10.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lightning-bolts==0.5.0
    - llvmlite==0.39.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - multidict==6.0.2
    - numba==0.56.4
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - omegaconf==2.2.3
    - packaging==21.3
    - pandas==1.5.2
    - pathtools==0.1.2
    - pillow==9.3.0
    - protobuf==3.20.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pynndescent==0.5.8
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytorch-lightning==1.6.4
    - pytz==2022.6
    - regex==2022.10.31
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - seaborn==0.12.1
    - sentry-sdk==1.11.1
    - smmap==5.0.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - timm==0.6.12
    - tokenizers==0.13.2
    - torch==1.13.0
    - torchmetrics==0.11.4
    - torchvision==0.14.0
    - tqdm==4.64.1
    - transformers==4.25.1
    - umap-learn==0.5.3
    - wandb==0.13.5
    - werkzeug==2.2.2
    - yarl==1.8.1
    - zipp==3.10.0
prefix: /home/.conda/envs/py38_ssl

